---
apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    app: ingress-test
    name: ingress-test
  name: ingress-test
spec:
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 5000
    protocol: TCP
    targetPort: 5000
    nodePort: 31000
  selector:
    app: ingress-test
  type: NodePort
---
apiVersion: v1
kind: Pod
metadata:
  annotations:
  labels:
    app: ingress-test
  name: ingresstest-pod
spec:
  containers:
  - image: infra.dt.vmw.run/apps/ingress-test:0.0
    imagePullPolicy: Always
    name: ingresstest-container
    ports:
    - containerPort: 5000
      name: http
      protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
  labels:
    app: ingress-test
  name: ingress-test
spec:
  ingressClassName: "contour"
  rules:
  - http:
      paths:
      - backend:
          service:
            name: ingress-test
            port:
              number: 5000
        path: /
        pathType: Prefix
